### ISSUE TITLE
To do when `bisonpicsuite` is public

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/bisonpicsuite#1]
```[tasklist]
### Tasks
- [x] Update actions to public
- [x] Check links in vignettes
- [x] Remove the secret
- [x] Update to the non private test coverage action.
- [x] Update actions to remove tokens
- [x] Check website works
```
